version: '3'

services:

    mysql:
        image: mysql:5.7
        container_name: pms_mysql
        volumes:
            - ./mysql:/var/lib/mysql
        restart: always
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: secret

    web:
        build: .
        container_name: pms_web
        volumes:
            - ./www:/var/www/html:cached
        restart: always
        ports:
            - 8080:80
        depends_on:
            - mysql