version: '3'

services:

    sqlserver:
        image: microsoft/mssql-server-linux:2017-CU12
        container_name: pms_sqlserver
        volumes:
            - ./mssql:/var/opt/mssql
        restart: always
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: Xx12Xxxxx12
        ports:
            - 1433:1433

    app:
        build: .
        container_name: pms_app
        volumes:
            - ./www:/var/www/html:cached
        restart: always
        ports:
            - 8181:80
        depends_on:
            - sqlserver